name: outsource_it_backend
description: Backend for Outsource it application

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  postgres: ^2.3.2
  build_runner: ^2.1.11
  shelf_cors_headers:
